config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  resources :records
  post "records/create_sample", to: "records#create_sample"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users

  resources :account_activations, only: [ :edit ]

  root to: "home#top"
  get "home/about", to: "home#about"
  get "home/information", to: "home#information"








  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/record.rb
# テスト要実装
class Record < ApplicationRecord
    validates :author_name, { presence: true }
    validates :main_title, { presence: true }
    validates :publish_date, { presence: true }
    validates :status, { presence: true }
    has_many :tag_relationships, dependent: :destroy
    has_many :tags, through: :tag_relationships
    belongs_to :user

    enum :status, { read: 0, unread: 1, unnecessary: 2 }, prefix: true

    # TODO: 日本語用のみ、英語対応のさい要修正。
    def get_title
        # TODO: 念の為、nilのケースも追加しておく
        if self.sub_title != ""
            title = "#{ self.main_title } 　━#{ self.sub_title }━"
        else
            title = "#{ self.main_title }"
        end
        title
    end

    def get_publication_title
        if self.publication_sub_title != ""
            publication_title = "#{ self.publication_main_title } 　━#{ self.publication_sub_title }━"
        else
            publication_title = "#{ self.publication_main_title }"
        end
        publication_title
    end

    def get_volume_and_number
        if self.volume && self.no
            volume_and_number = "第#{ volume }巻 第#{ no }号"
        elsif self.volume
            volume_and_number = "第#{ volume }巻"
        elsif self.no
            volume_and_number = "第#{ no }号"
        else voliume_and_number = nil
        end
        volume_and_number
    end

    # 同じタグを持つレコードを返すメソッド
    # TODO: 検索されたタグしか返せなくなる？要検証。
    def self.tagged_with(tag_name, user)
        tag = Tag.find_by(name: tag_name)
        return [] unless tag
        user.records.joins(:tags).where(tags: { id: tag.id })
    end

    # 新規タグづけ用のメソッド
    def save_tags(tags)
        TagManager.new(self, tags).save_tags
    end
    # タグ更新用のメソッド
    def update_tags(latest_tags)
        TagManager.new(self, latest_tags).update_tags
    end

    private
        # ransack検索フォーム用クラスメソッド
        def self.ransackable_attributes(auth_object = nil)[
            "author_name",
            "main_title",
            "sub_title",
            "publisher",
            "publication_main_title",
            "publication_sub_title",
            "compiled_by",
            "memo",
            "created_at",
            "no",
            "publish_date",
            "status",
            "volume",
            "volume_other_form"
        ]
        end

        def self.ransackable_associations(auth_object = nil)
            [ "tag_relationships", "tags", "user" ]
        end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  include RecordsHelper
  before_action :logged_in_user
  before_action :ensure_correct_user, { only: [ :edit, :update, :destroy ] }

  def index
    @q = current_user.records.ransack(search_params)
    # タグ検索がなされた場合
    if params[:tag_name].present?
      @tag_name = params[:tag_name].to_s.strip.downcase # 念の為正規化
      records = Record.tagged_with(@tag_name, current_user)
    # キーワード検索がなされた場合
    else
      records = @q.result(distinct: true)
    end
    @records = records.order(:publish_date)
               .includes(:tags) # タグをロード
               .paginate(page: params[:page], per_page: 20)
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    tags_array = extract_tags(tag_params[:tags]) # 入力したタグ名を受け取る（タグだけテーブルが異なるため）
    @record.user_id = current_user.id
    if @record.save
      @record.save_tags(tags_array)
      flash[:success] = "登録に成功しました"
      redirect_to records_path
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @record = Record.find_by(id: params[:id])
    @tags = @record.tags.pluck(:name).join(",")
  end

  def update
    @record = Record.find_by(id: params[:id])
    tags_array = extract_tags(tag_params[:tags])
    if @record.update(record_params)
      @record.update_tags(tags_array)
      flash[:success] = "書誌情報を更新しました"
      redirect_to records_path
    else
      flash.now[:denger] = "書誌情報の更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def create_sample
    SampleRecordsCreater.new(current_user).call
    flash[:info] = "サンプルデータを追加しました"
    redirect_to records_path
  end

  def destroy
    @record = Record.find_by(id: params[:id])
    @record.destroy
    flash[:success] ="書誌情報を削除しました"
    redirect_to records_path, status: :see_other
  end

  private
    def record_params
      params.expect(record: [
        :user_id, :author_name, :main_title, :sub_title, :publish_date, :publisher,
        :compiled_by, :publication_main_title, :publication_sub_title,
        :volume, :no, :volume_other_form, :memo, :type, :status
    ])
    end

    def tag_params
      params.expect(record: [ :tags ])
    end

    # ransack検索用のparams
    # TODO: 検索カラムを切り出し
    def search_params
      if params[:q].present?
        params.require(:q).permit(
          # フリーワード検索
          :author_name_or_main_title_or_sub_title_or_publisher_or_publication_main_title_or_publication_sub_title_or_compiled_by_or_memo_cont,
          # 著者・編者で検索
          :author_name_or_compiled_by_cont,
          # タイトルで検索
          :main_title_or_sub_title_cont,
          # 出版物タイトルで検索
          :publication_main_title_or_publication_sub_title_or_volume_other_form_cont,
          # 出版社で検索
          :publisher_cont,
          # 出版期間で検索
          :publish_date_gteq,
          :publish_date_lteq,
          # 既読・未読・不必要で絞り込み
          :status_eq,
          # メモで検索
          :memo_cont
        )
      else
        {} # params[:q] がない場合、空のハッシュを返す
      end
    end

    # tag検索用のparams処理
    def tag_search_params
      params.permit(:tag_name)
    end

    # 以下、before_action
    def ensure_correct_user
      @record = Record.find_by(id: params[:id])
      if @record.user_id != current_user.id
        flash[:danger] = "権限がありません"
        redirect_to records_path, status: :see_other
      end
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url, status: :see_other
      end
    end
end

app/helpers/records_helper.rb
module RecordsHelper
    def extract_tags(tags)
        tags = tags.presence || ""
        tags.split(",").map(&:strip)
    end
end

app/views/records/_add_sample_records_button.html.erb
<%= form_with scope: :record, url: records_create_sample_path, method: :post do %>
<div class="col-12 text-center">
    <h5 class="my-5">まだ書誌情報がありません。</h5>
    <button type="submit" class="btn btn-secondary btn-lg my-5">サンプルデータを入力</button>
    <p class="my-5">（3件の著書、2件の論文のデータがサンプルとして入力されます。）</p>
</div>
<% end %>

app/views/records/_book_info.html.erb
<div class="col ms-2 me-2" style="width:85%;">  
  <div>
    <h5 class="fw-bold py-2 bg-secondary bg-opacity-10 border-bottom mt-2">
      <span class="fa fa-book px-2" style=" font-size:25px;"></span> <%=record.author_name %>（<%= record.publish_date %>）
    </h5>
  </div>
  <h5 class="ms-4 fw-bold" style=" font-size:18px;">『 <%= record.get_title %> 』<%= record.volume_other_form %></h5>
  <p class="ms-5 text-secondary"><%= record.publisher %></p>
</div>
<div class="col-1 float-end smt-3  mt-2 ms-4">
<h5><span class="badge bg-primary rounded-pill fw-normal"><%= record.human_attribute_enum(:status) %></span></h5>
</div>

app/views/records/_book_registration.html.erb
<!-- createアクションの場合とupdateアクションの場合で処理を分岐 -->
<%= form_with model: @record, scope: :record, url: @record.new_record? ? records_path : record_path(@record),
              local: true, method: @record.new_record? ? :post : :patch do |f| %>
<%= f.hidden_field :type, value: "Book" %>
  <div class="input-group mb-3 p-4 pb-5 <%= @record.new_record? ? "border border-top-0" : "border" %> rounded-1 shadow-sm">
    <h5 class="fw-bold pb-3 mb-4 col-12 border-bottom border-secondary border-2"><span class="fa fa-book fa-lg pe-2"></span> 著書情報</h5>
    <div class="row g-3 needs-validation" novalidate>

      <%= render "records/forms/general", f: f %>
      
      <div class="col-md-8 mt-5">
        <%= f.label :volume_other_form, "巻号その他（任意）", class: "form-label" %>
        <%= f.text_field :volume_other_form, class: "form-control border-dark-subtle", placeholder: "1988年秋号 〇〇講座第2巻 など、-巻-号で表せない場合" %>
      </div>
      <div class="col-md-6 pe-5 mt-3">
        <%= f.label :publisher, "出版社", class: "form-label" %>
        <%= f.text_field :publisher, class: "form-control border-dark-subtle", required: true %>
      </div>
      <%= render "status_form", f: f %>
      
      <%= render "records/forms/details", f: f %>

      <div class="d-grid gap-2 mt-4 col-6 mx-auto">
        <%= f.submit "#{submit_btn}", class: "btn btn-primary btn-lg mt-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/records/_compilation_registration.html.erb
<%= form_with model: @record, scope: :record, url: @record.new_record? ? records_path : record_path(@record),
              local: true, method: @record.new_record? ? :post : :patch do |f| %>
<%= f.hidden_field :type, value: "Compilation" %>
  <div class="input-group mb-3 p-4 pb-5 <%= @record.new_record? ? "border border-top-0" : "border" %> rounded-1 shadow-sm">
    <h5 class="fw-bold pb-3 mb-4 col-12 border-bottom border-secondary border-2"> <span class="fa fa-file pe-2"></span> 論文情報</h5>
    <div class="row g-3 needs-validation" novalidate>

    <%= render "records/forms/general", f: f %>

      <h5 class="fw-bold mt-3 mb-4 py-3 col-12 border-bottom border-secondary border-2"><span class="fa fa-book fa-lg pe-2"></span> 収録物情報</h5>
      <div class="col-8">
        <%= f.label :compiled_by, "編者名", class: "form-label" %>
          <%= f.text_field :compiled_by, class: "form-control border-dark-subtle", required: true %>
      </div>
    

      <div class="col-12 py-2">収録物タイトル</div>
      <div class="input-group col-md-12 pe-4">
        <%= f.text_field :publication_main_title, class: "form-control border-dark-subtle", placeholder: "主題", required: true %>
        <span class="input-group-text">：</span>
        <%= f.text_field :publication_sub_title, class: "form-control border-dark-subtle", placeholder: "副題" %>
      </div>
      <div class="mt-3 pe-5 col-md-4">
        <label class="form-label">巻号（半角数字）</label>
        <!-- 全角数字を弾くようにする、もしくは半角に置き換える -->
        <div class="input-group">
          <span class="input-group-text">第</span>
          <%= f.number_field :volume, class: "form-control border-dark-subtle col-1" %>
          <span class="input-group-text">巻</span>
          <%= f.number_field :no, class: "form-control border-dark-subtle col-1" %>
          <span class="input-group-text">号</span>
        </div>
      </div>

      <div class="col-md-6 mt-3">
        <%= f.label :volume_other_form, "巻号その他（任意）", class: "form-label" %>
        <%= f.text_field :volume_other_form, class: "form-control border-dark-subtle", placeholder: "1988年秋号 〇〇講座第2巻 など、-巻-号で表せない場合", value: "#{ @record.volume_other_form }" %>
      </div>

      <div class="col-md-4 pe-5 mt-3">
        <%= f.label :publisher, "出版社", class: "form-label" %>
          <%= f.text_field :publisher, class: "form-control border-dark-subtle", required: true %>
      </div>

      <%= render "status_form", f: f %>

      <%= render "records/forms/details", f: f %>

      <div class="d-grid gap-2 mt-4 col-6 mx-auto">
        <%= f.submit "#{submit_btn}", class: "btn btn-primary btn-lg mt-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/records/_delete_btn.html.erb
  <%= form_with url: record_path(record), method: :delete do %>
  <button type="button" class="delete-record-btn btn btn-outline-danger btn-sm mt-2 px-3" data-bs-toggle="modal" data-bs-target="#delete-confirmation-<%= record.id %>">
    削除
  </button>
  <div class="modal fade" id="delete-confirmation-<%= record.id %>" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="ModalLabel">確認</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          本当に削除しますか？
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">いいえ</button>
          <button type="submit" class="btn btn-primary">はい</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/records/_error_messages.html.erb
<% if @record.errors.full_messages %>
<div class="error-alert">
    <ul>
      <% @record.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
</div>
<% end %>

app/views/records/_more_information_form.html.erb
<div class="accordion accordion-flush col-12 mt-3 p-0 border-top" id="accordionFlush">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed ps-4" style="font-weight:bold; font-size:20px;" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          <i class="fas fa-pen me-3"></i>詳細の入力
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlush">
        <div class="accordion-body">
          <%= f.label :tags, "タグ", class: "form-label"%>
          <%= f.text_field :tags, size: "70x5", class: "form-control border-dark-subtle",
                           placeholder: "タグが複数の場合は,(半角カンマ)で区切ってください",
                           value: f.object.tags.present? ? f.object.tags.pluck(:name).join(",") : "" %>
          <%= f.label :memo, "メモ", class: "form-label mt-3"%>
          <%= f.text_area :memo, size: "70x5", class: "form-control border-dark-subtle",
                           value: f.object.memo.present? ? f.object.memo : "" %>
        </div>
      </div>
    </div>
</div>

app/views/records/_paper_info.html.erb
<div class="col ms-2 me-2" style="width:85%;">  
    <div>
      <h5 class="fw-bold py-2 bg-secondary bg-opacity-10 mt-2">
        <span class="fa fa-file px-2" style=" font-size:25px;"></span> <%=record.author_name %>（<%= record.publish_date %>）
      </h5>
    </div>
    <h5 class="ms-4 fw-bold" style=" font-size:18px;">「 <%= record.get_title %> 」</h5>
    <p class="ms-5 text-secondary"><%= record.compiled_by %>『<%= record.get_publication_title %>』<%= record.get_volume_and_number %><%= record.volume_other_form %><%= ", #{record.publisher}" %></p>
  </div>
  <div class="col-1 float-end smt-3  mt-2 ms-4">
  <h5><span class="badge bg-primary rounded-pill fw-normal"><%= record.human_attribute_enum(:status) %></span></h5>
</div>

app/views/records/_paper_registration.html.erb
<%= form_with model: @record, scope: :record, url: @record.new_record? ? records_path : record_path(@record),
              local: true, method: @record.new_record? ? :post : :patch do |f| %>
<%= f.hidden_field :type, value: "Paper" %>
<div class="input-group mb-3 p-4 pb-5 <%= @record.new_record? ? "border border-top-0" : "border" %> rounded-1 shadow-sm">
    <h5 class="fw-bold pb-3 mb-4 col-12 border-bottom border-secondary border-2"><i class="fa fa-file pe-2"></i> 論文情報</h5>
    <div class="row g-3 needs-validation"novalidate>
      
      <%= render "records/forms/general", f: f %>
      
      <h5 class="fw-bold mt-3 mb-4 py-3 col-12 border-bottom border-secondary border-2"><span class="fa fa-book fa-lg pe-2"></span> 収録物情報</h5>
      <div class="col-8">
        <%= f.label :compiled_by, "編者名", class: "form-label" %>
        <%= f.text_field :compiled_by, class: "form-control border-dark-subtle", required: true %>
      </div>
      <div class="col-12 py-2">雑誌タイトル</div>
      <div class="input-group col-md-12 pe-4">
        <%= f.text_field :publication_main_title, class: "form-control border-dark-subtle", placeholder: "主題", required: true %>
        <span class="input-group-text">：</span>
        <%= f.text_field :publication_sub_title, class: "form-control border-dark-subtle", placeholder: "副題" %>
      </div>
      <div class="mt-3 pe-5 col-md-4">
        <!-- 全角数字を弾くようにする、もしくは半角に置き換える -->
        <label class="form-label">巻号（半角数字）</label>
        <div class="input-group">
          <span class="input-group-text">第</span>
          <%= f.number_field :volume, class: "form-control border-dark-subtle col-1" %>
          <span class="input-group-text">巻</span>
          <%= f.number_field :no, class: "form-control border-dark-subtle col-1" %>
          <span class="input-group-text">号</span>
        </div>
      </div>
      <div class="col-md-6 mt-3">
        <%= f.label :volume_other_form, "巻号その他（任意）", class: "form-label" %>
        <%= f.text_field :volume_other_form, class: "form-control border-dark-subtle", placeholder: "1988年秋号 〇〇講座第2巻 など、-巻-号で表せない場合" %>
      </div>
      <div class="col-md-4 pe-5 mt-3">
        <%= f.label :publisher, "出版社", class: "form-label" %>
        <%= f.text_field :publisher, class: "form-control border-dark-subtle" %>
      </div>
      <%= render "status_form", f: f %>

      <%= render "records/forms/details", f: f %>

      <div class="d-grid gap-2 mt-4 col-6 mx-auto">
        <%= f.submit "#{submit_btn}", class: "btn btn-primary btn-lg mt-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/records/_records_tags_button.html.erb
<% unless record.tags.empty? %>
    <% record.tags.each do |tag| %>
        <div style="display:inline-block">
            <%= form_with local: true, method: :get do |f| %>
                <%= f.hidden_field :tag_name, value: tag.name %>
                <button type="submit" class="btn text-bg-secondary rounded-pill" style="font-weight:normal; font-size:14px;" id="button-addon">
                    <span class="fa fa-tag pe-2"></span><%= tag.name %>
                </button>
            <% end %>
        </div>
    <% end %>
<% end %>                        

app/views/records/_search_form.html.erb
<%= search_form_for @q do |f| %>
<!-- フリーワード検索 -->
 <div class="row">
  <div class="free-word-search input-group mb-4 ps-2 w-75">
    <!-- リファクタリングの余地あり、しかしransack_aliasが機能しない -->
    <%= f.search_field :author_name_or_main_title_or_sub_title_or_publisher_or_publication_main_title_or_publication_sub_title_or_compiled_by_or_memo_cont,
                      class: "form-control border-primary border-1", placeholder: "フリーワード検索", aria: { describedby: "button-addon" } %>
                    
    <%= f.submit "検索", class: "btn btn-primary px-5", id: "button-addon" %>
  </div>
  <!-- 詳細検索アコーディオンのトリガーボタン -->
  <div class="w-25" style="line-height:38px;">
    <button class="border-0 btn btn-link-dark btn-sm" style="font-size:16px;" type="button" data-bs-toggle="collapse" data-bs-target="#search-collapse" aria-expanded="false" aria-controls="search-collapse">
      詳細検索
    </button>
  </div>

</div>

<!-- 詳細検索フォーム（アコーディオンの中身のみ） -->
 <%= render "detail_search_form", f: f %>

<% end %>

app/views/records/edit.html.erb
<% provide(:title, "文献情報の編集") %>
<div class="main-contents">
  <h2 class="mt-4 mb-2">書誌情報の変更</h2>
  <div style="float:left;">
  <%= link_to "一覧に戻る", records_path, class: "ms-3 link-underline link-underline-opacity-0" %>
  </div>
  <%= render "error_messages"%>

  <div class="container mt-5">
  <!-- bookの編集フォーム -->
    <% if @record.type == "Book" %>
      <%= render "records/forms/book", submit_btn: "更新" %>
  <!-- paperの編集フォーム -->
    <% elsif @record.type == "Paper"%>
      <%= render "records/forms/paper", submit_btn: "更新" %>
  <!-- compilationの編集フォーム -->
    <% else %>
      <%= render "records/forms/paper", submit_btn: "更新" %>
    <% end %>            
  </div>

  <!-- 削除ボタンと警告モーダル(edit用) -->
  <div class="mx-auto p-2 mt-4" style="width: 200px;">
  <%= form_with url: record_path(@record), method: :delete  do %>
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#delete-confirmation">
      書誌情報を削除する
    </button>
    <div class="modal fade" id="delete-confirmation" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="ModalLabel">確認</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            本当に削除しますか？
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">いいえ</button>
            <button type="submit" class="btn btn-primary">はい</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/records/index.html.erb
<% provide(:title, "文献の一覧・検索") %>
<div class="container-fluid">
  <h2 class="my-4">文献の一覧・検索</h1>

  <!-- 検索フォーム -->
  <%= render "records/search_forms/freewords" %>

  <!-- TODO: リファクタリング対象 -->
  <div class="bib-list mb-1" style="width:100%;">
    <div>
      <!-- タグクリックによる絞り込み結果 -->
      <% if @tag_name.present? %>
        <%= "タグ：「#{@tag_name}」" %>

      <!-- フリーワード検索による絞り込み結果 -->
      <% elsif @q.author_name_or_main_title_or_sub_title_or_publisher_or_publication_main_title_or_publication_sub_title_or_compiled_by_or_memo_cont.present? %>
      <%= "「#{@q.author_name_or_main_title_or_sub_title_or_publisher_or_publication_main_title_or_publication_sub_title_or_compiled_by_or_memo_cont}」の検索結果" %>
      <% end %>
    </div>

    <!-- 取得レコードの件数表示、および戻るボタン -->
    <div class="ms-3">
      <p class="my-2" style="display:inline-block;">全 <%= @records.count %> 件の文献情報</p>
      <%= link_to "（一覧に戻る）", records_path, class: "link-underline link-underline-opacity-0", style: "display:inline-block;" unless @q.nil? && @tag_name.nil? %>
    </div>
  </div>

  <!-- レコード一覧 -->
  <div>
    <%= will_paginate @records %>
    <!-- ユーザーが保持する文献情報がない場合のみ、サンプル入力ボタンを表示 -->
    <% if current_user.records.empty? %>
      <%= render "records/buttons/add_sample"%>
    <% end %>

    <!-- 文献一覧 -->
    <ul class="list-group mt-2">
      <% @records.each do |record| %>
        <li class="row list-group-item d-flex justify-content-between align-items-start shadow-sm mb-1 me-4 p-0 w-100">
          <div class="accordion accordion-flush w-100 px-0" id="accordionFlushExample">
            <div class="accordion-item" style="border-radius:5px 5px 5px 5px;">
              <!-- 基本情報 -->
              <h2 class="accordion-header" >
                <button class="accordion-button collapsed border py-0 ps-1 border-bottom-0" style="border-radius:5px 5px 0px 0px;" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= record.id%>" aria-expanded="false" aria-controls="flush-collapse<%= record.id%>">
                  <% case record.type %>
                  <% when "Compilation", "Paper" %>
                    <%= render "records/infos/paper", record: record %>
                  <% when "Book" %>
                    <%= render "records/infos/book", record: record %>
                  <% end %>
                </button>
              </h2>
              <!-- 詳細情報（アコーディオン） -->
              <div id="flush-collapse<%= record.id%>" class="accordion-collapse collapse border">
                <div class="row justify-content-end accordion-body w-100">
                  <div class="col">
                    <!-- タグ表示 -->
                    <%= render "records/buttons/tags", record: record %>
                      
                    <!-- メモ表示 -->
                    <div class="mt-4">
                      メモ：
                      <%= record.memo %>
                    </div>
                  </div>
                  <!-- 更新・削除ボタン -->
                  <div class="col-1 mx-1">
                    <%= link_to "更新", edit_record_path(record), class: "col btn btn-outline-secondary btn-sm mt-2 px-3" %>
                    <%= render "records/buttons/delete", record: record %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="mt-5">
    <%= will_paginate @records %>
  </div>
</div>

app/views/records/new.html.erb
<% provide(:title, "文献情報の入力") %>
<div class="main-contents mx-2">
  <h2 class="my-4">文献情報の入力</h2>

  <%= render "error_messages"%>
  
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="book-tab" data-bs-toggle="tab" data-bs-target="#book-tab-pane" type="button" role="tab" aria-controls="book-tab-pane" aria-selected="true">著書</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="paper-tab" data-bs-toggle="tab" data-bs-target="#paper-tab-pane" type="button" role="tab" aria-controls="paper-tab-pane" aria-selected="false">雑誌論文</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="compilation-tab" data-bs-toggle="tab" data-bs-target="#compilation-tab-pane" type="button" role="tab" aria-controls="compilation-tab-pane" aria-selected="false">編著論文</button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <!-- 著書タブ -->
    <div class="tab-pane fade show active" id="book-tab-pane" role="tabpanel" aria-labelledby="book-tab" tabindex="0">
      <%= render "records/forms/book", submit_btn: "著書として登録" %>
    </div>

    <!-- 雑誌論文タブ -->
    <div class="tab-pane fade" id="paper-tab-pane" role="tabpanel" aria-labelledby="paper-tab" tabindex="0">
      <%= render "records/forms/paper", submit_btn: "雑誌論文として登録" %>
    </div>

    <!-- 編著論文タブ -->
    <div class="tab-pane fade" id="compilation-tab-pane" role="tabpanel" aria-labelledby="compilation-tab" tabindex="0">
      <%= render "records/forms/compilation", submit_btn: "編著論文として登録" %>
    </div>
  </div>
</div>