config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  resources :records
  post "records/create_sample", to: "records#create_sample"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users

  resources :account_activations, only: [ :edit ]

  root to: "home#top"
  get "home/about", to: "home#about"
  get "home/information", to: "home#information"








  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.full_messages %>
    <div class="error-alert">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <nav class="bg-body-tertiary bg-primary" data-bs-theme="dark" style="height:250px; margin-top:150px; padding-bottom:50px;">
      <div class="container-fluid text-center pt-4">
        <small style="color:white;">© 2024 JemRef</small>
      </div>
    </nav>
</footer>

app/views/layouts/_form.html.erb
<%= form_with model: @user, data: { turbo: false } do |f|%>
<div class="px-4 mt-2">
  <div class="col-12 mt-4">
    <%= f.label :name, "名前（ニックネーム）", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>
<div class="px-4 mt-2">
  <div class="col-12 mt-4">
    <%= f.label :email, "メールアドレス", class: "form-label"  %>
    <%= f.email_field :email, class: "form-control"  %>
  </div>
</div>
<div class="px-4 mt-2">
  <div class="col-12 mt-4">
    <%= f.label :password, "パスワード", class: "form-label"  %>
    <%= f.password_field :password, class: "form-control"  %>
  </div>
  <div class="col-12 mt-4">
    <%= f.label :password_confirmation, "パスワード（確認用）", class: "form-label"  %>
    <%= f.password_field :password_confirmation, class: "form-control"  %>
  </div>
</div>
<div class="text-center">
  <%= f.submit yield(:button_text), class: "btn btn-lg btn-primary mt-4 px-5"%>
</div>
<% end %>

app/views/layouts/_head.html.erb
<head>
    <meta name="discription" content="JemRefは、人文・社会科学系分野の和文文献の書誌情報整理に特化したツールです。現在、試験運用中です。">
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <%= favicon_link_tag("jemref.png") %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
</head>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
    <% if logged_in? %>
      <%= link_to "JemRef", records_path, class:"navbar-brand px-4 fs-2 fw-bold" %>
    <% else %>
      <%= link_to "JemRef", root_path, class:"navbar-brand px-4 fs-2 fw-bold" %>
    <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <!-- ログイン時のナビゲーションバー -->
        <% if logged_in? %>
        <%= render "layouts/logged_in_header" %>
        
        <!-- 非ログイン時のナビゲーションバー -->
        <% else %>
        <%= render "layouts/not_logged_in_header" %>
        
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_logged_in_header.html.erb
<!-- 左づめメニュー -->
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item ps-2">
    <%= link_to "文献の一覧・検索", records_path, class: "nav-link pe-3" %>
  </li>
  <li class="nav-item ps-2">
    <%= link_to "文献情報の入力", new_record_path, class: "nav-link pe-3" %>
  </li>
</ul>
<!-- 右づめメニュー -->
<div class="d-flex navbar-nav">
  <li class="nav-item me-4">
    <%= link_to home_about_path, class: "nav-link pe-3", title: "使い方" do %>
    <i class="fa-regular fa-circle-question fs-5"></i>
    <% end %>
  </li>
  <li class="nav-item me-4">
    <%= link_to home_information_path, class: "nav-link pe-3", title: "お知らせ・お問い合わせ" do %>
    <i class="fa fa-info fs-5"></i>
    <% end %>
  </li>
  <li class="nav-item dropdown me-5">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">アカウント</a>
    <ul class="dropdown-menu  me-5" style="width: 200px;">
      <li><p class="ps-3">現在のユーザー </p></li>
      <li><p class="ps-4"><span class="fa fa-user pe-2" style="color:white;"></span> <%= @current_user.name %></p></li>
      <li><hr class="dropdown-divider mb-3"></li>
      <li><%= link_to "情報の編集", edit_user_path(current_user), class: "dropdown-item ps-4 mb-3" %></li>
      <li><%= link_to "ログアウト", logout_path, class: "dropdown-item ps-4 mb-3",
                                  data: { "turbo-method": :delete } %></li>
    </ul>
  </li>
</div>

app/views/layouts/_not_logged_in_header.html.erb
<!-- 左づめメニュー -->
<ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
<!-- 右づめメニュー -->
<div class="d-flex navbar-nav">
    <li class="nav-item me-4">
        <%= link_to home_about_path, class: "nav-link pe-3", title: "使い方" do %>
        <i class="fa-regular fa-circle-question fs-5"></i>
        <% end %>
      </li>
      <li class="nav-item me-4">
        <%= link_to home_information_path, class: "nav-link pe-3", title: "お知らせ・お問い合わせ" do %>
        <i class="fas fa-info fs-5"></i>
        <% end %>
      </li>
  <li class="nav-item">
    <%= link_to "ログイン", login_path, class: "nav-link pe-3" %>
  </li>
  <li class="nav-item">
    <%= link_to "新規登録", signup_path, class: "nav-link pe-3" %>
  </li>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= yield :head %>
  <%= render "layouts/head" %>
  <body>
    <%= render "layouts/header" %>
  <main class="container my-3">
    <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
    </div>
    <div class="container-fluid">
        <div class="main-contents-wrapper">
          <%= yield %>
        </div>
    </div>
  </main>
  <%= render "layouts/footer" %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>